# Generated by Django 5.0 on 2025-03-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_conversation_message_messageimage_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, help_text='Аккаунт заблокирован до', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткая информация о пользователе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deals_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество завершенных сделок'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Количество неудачных попыток входа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP-адрес последнего входа', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_session_start',
            field=models.DateTimeField(blank=True, help_text='Начало последней сессии', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Город/страна пользователя', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='offers_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество созданных предложений'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Формат: +7XXXXXXXXXX', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Рейтинг пользователя', max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP-адрес при регистрации', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_logins',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество входов в систему'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_time_online',
            field=models.DurationField(blank=True, help_text='Общее время онлайн', null=True),
        ),
    ]
