# Generated by Django 5.1.7 on 2025-03-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_userprofile_account_locked_until_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Включена ли двухфакторная аутентификация'),
        ),
    ]
