# Generated by Django 5.1.7 on 2025-03-28 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_userprofile_two_factor_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_log',
            field=models.JSONField(blank=True, default=dict, help_text='Журнал активности пользователя по дням', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Подтвержден ли аккаунт продавца'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='Дата верификации аккаунта', null=True),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Вход в систему'), ('offer_create', 'Создание предложения'), ('offer_update', 'Обновление предложения'), ('offer_delete', 'Удаление предложения'), ('review', 'Оставлен отзыв'), ('deal', 'Завершена сделка'), ('profile_update', 'Обновление профиля'), ('message', 'Отправлено сообщение')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
