# Generated by Django 5.1.7 on 2025-03-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_add_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purchases_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество совершенных покупок'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество совершенных продаж'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deals_count',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество завершенных сделок (устаревшее)'),
        ),
    ]
