# Generated by Django 5.1.7 on 2025-03-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0007_gamecategory_remove_game_cover_image_game_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gameapp.game'),
        ),
        migrations.AlterUniqueTogether(
            name='gamecategory',
            unique_together={('game', 'slug')},
        ),
    ]
