# Generated by Django 5.1.7 on 2025-03-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_gamecategory_game_alter_gamecategory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('filter_type', models.CharField(choices=[('select', 'Выпадающий список'), ('checkbox', 'Флажки'), ('radio', 'Переключатели'), ('range', 'Диапазон')], default='select', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_groups', to='gameapp.gamecategory')),
            ],
            options={
                'verbose_name': 'Группа фильтров',
                'verbose_name_plural': 'Группы фильтров',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('filter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gameapp.filtergroup')),
            ],
            options={
                'verbose_name': 'Опция фильтра',
                'verbose_name_plural': 'Опции фильтров',
                'ordering': ['filter_group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.filteroption')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='gameapp.offer')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтров',
                'unique_together': {('offer', 'filter_option')},
            },
        ),
    ]
