# Generated by Django 5.1.7 on 2025-03-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0012_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='related_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='related_payment',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userviewhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userviewhistory',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='userviewhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='forwarded_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_forwarded',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('quality', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20)),
                ('is_tradable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='gameapp.gamecategory')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gameapp.game')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='gameapp.gamesubcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='UserViewHistory',
        ),
    ]
